// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fybgqcwrmlvnyrevgjdp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ5YmdxY3dybWx2bnlyZXZnamRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMjAxMDAsImV4cCI6MjA2ODU5NjEwMH0.aO0kKZrYd62gHX2yyeGC7qgDthQJhAq4uZltggUBcrA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});